import React, { useState } from 'react';
import { Download, Upload, FileCode, Smartphone, Globe } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';

interface ExportPanelProps {
  code: string;
}

export const ExportPanel = ({ code }: ExportPanelProps) => {
  const [isExporting, setIsExporting] = useState(false);

  const exportOptions = [
    { id: 'html', label: 'HTML/CSS/JS', icon: FileCode, description: 'Pure web files ready for any hosting' },
    { id: 'react', label: 'React Project', icon: Smartphone, description: 'Modern React application structure' },
    { id: 'wordpress', label: 'WordPress Theme', icon: Globe, description: 'Ready-to-install WordPress theme' }
  ];

  const uploadWebsiteToSupabase = async (htmlContent: string) => {
    const fileName = `website-${Date.now()}.html`;
    
    // Create a file blob
    const file = new File([htmlContent], fileName, { type: 'text/html' });
    
    // Upload to Supabase Storage
    const { data, error } = await supabase.storage
      .from('websites')
      .upload(fileName, file, {
        cacheControl: '3600',
        upsert: false
      });

    if (error) throw error;
    
    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('websites')
      .getPublicUrl(fileName);
    
    return publicUrl;
  };

  const handleExport = async (type: string) => {
    if (!code) {
      toast.error('No code to export');
      return;
    }

    setIsExporting(true);

    try {
      let exportContent = code;
      let filename = 'website';

      switch (type) {
        case 'html':
          filename = 'website.html';
          break;
        case 'react':
          exportContent = generateReactProject(code);
          filename = 'react-project.zip';
          break;
        case 'wordpress':
          exportContent = generateWordPressTheme(code);
          filename = 'wordpress-theme.zip';
          break;
      }

      const blob = new Blob([exportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast.success(`${type.toUpperCase()} export completed!`);
    } catch (error) {
      toast.error('Export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const handleDirectUpload = async () => {
    if (!code) {
      toast.error('No code to upload');
      return;
    }

    setIsExporting(true);

    try {
      toast.success('Uploading website...');
      const publicUrl = await uploadWebsiteToSupabase(code);
      
      toast.success('🎉 Website uploaded successfully!');
      toast.success(`📱 Live URL: ${publicUrl}`);
      await navigator.clipboard.writeText(publicUrl);
      toast.success('Website URL copied to clipboard!');
    } catch (error) {
      console.error('Upload error:', error);
      toast.error('Upload failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const generateReactProject = (htmlCode: string) => {
    return `// React Project Structure
// App.js
import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      ${htmlCode.replace(/<[^>]*>/g, '')}
    </div>
  );
}

export default App;`;
  };

  const generateWordPressTheme = (htmlCode: string) => {
    return `<?php
// WordPress Theme: Generated by Zeus AI Coder
// style.css
/*
Theme Name: Zeus AI Generated Theme
Description: Auto-generated WordPress theme
Version: 1.0
*/

// index.php
<?php get_header(); ?>
${htmlCode}
<?php get_footer(); ?>`;
  };

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h3 className="text-xl font-semibold text-white mb-2">Export Your Website</h3>
        <p className="text-slate-400">Choose your preferred format and deployment method</p>
      </div>

      <div className="grid md:grid-cols-3 gap-4">
        {exportOptions.map((option) => {
          const IconComponent = option.icon;
          return (
            <button
              key={option.id}
              onClick={() => handleExport(option.id)}
              disabled={isExporting || !code}
              className="bg-slate-800/50 hover:bg-slate-700/50 border border-slate-600 hover:border-slate-500 rounded-lg p-4 text-left transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <div className="flex items-center space-x-3 mb-3">
                <IconComponent className="w-6 h-6 text-blue-400" />
                <h4 className="font-semibold text-white">{option.label}</h4>
              </div>
              <p className="text-sm text-slate-400">{option.description}</p>
            </button>
          );
        })}
      </div>

      <div className="bg-gradient-to-r from-slate-800/50 to-purple-900/30 rounded-lg p-4 border border-purple-500/20">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <Upload className="w-6 h-6 text-white" />
            <div>
              <h4 className="font-semibold text-white">Direct Website Upload</h4>
              <p className="text-sm text-slate-400">Upload your website and get a live link instantly</p>
            </div>
          </div>
          <button
            onClick={handleDirectUpload}
            disabled={isExporting || !code}
            className="bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white px-4 py-2 rounded-lg transition-colors"
          >
            {isExporting ? 'Uploading...' : 'Upload & Share'}
          </button>
        </div>
      </div>

      {!code && (
        <div className="text-center text-slate-500 py-8">
          <Download className="w-12 h-12 mx-auto mb-4 opacity-50" />
          <p>Generate or write some code first to enable export options</p>
        </div>
      )}
    </div>
  );
};
