// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqkkcaognqveamkibuek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxa2tjYW9nbnF2ZWFta2lidWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjEzMTgsImV4cCI6MjA2OTE5NzMxOH0.eZhWoK_iH2U8S3dBkZ0qnq0V6TMAnMdHwU4MW_N4KYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});